/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LegacyKeeper {
  export type BeneficiaryStruct = {
    wallet: AddressLike;
    shareBps: BigNumberish;
    registered: boolean;
  };

  export type BeneficiaryStructOutput = [
    wallet: string,
    shareBps: bigint,
    registered: boolean
  ] & { wallet: string; shareBps: bigint; registered: boolean };
}

export interface LegacyKeeperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addBeneficiary"
      | "beneficiaries"
      | "cancelInheritance"
      | "evacuate"
      | "evacuationExecuted"
      | "evacuationTimestamp"
      | "executeInheritance"
      | "getBeneficiaries"
      | "getContractBalance"
      | "getLivenessStatus"
      | "getTimeoutStatus"
      | "heartbeat"
      | "inheritanceExecuted"
      | "inheritanceTimestamp"
      | "isBeneficiary"
      | "liveness"
      | "onHeartbeatMissed"
      | "owner"
      | "panicButton"
      | "registerRecoveryKey"
      | "removeBeneficiary"
      | "setLivenessConfig"
      | "setSafeVault"
      | "startGracePeriod"
      | "toggleLiveness"
      | "transferOwnership"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BeneficiaryAdded"
      | "BeneficiaryRemoved"
      | "ConfigUpdated"
      | "EvacuationTriggered"
      | "GracePeriodStarted"
      | "HeartbeatMissed"
      | "HeartbeatRecorded"
      | "InheritanceExecuted"
      | "InheritanceTransfer"
      | "PanicButtonPressed"
      | "RecoveryKeyRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addBeneficiary",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beneficiaries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelInheritance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evacuate",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "evacuationExecuted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evacuationTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeInheritance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLivenessStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeoutStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "heartbeat",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "inheritanceExecuted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inheritanceTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "liveness", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onHeartbeatMissed",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "panicButton",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRecoveryKey",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLivenessConfig",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSafeVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startGracePeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleLiveness",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelInheritance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "evacuate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "evacuationExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evacuationTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeInheritance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLivenessStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeoutStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "heartbeat", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inheritanceExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inheritanceTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liveness", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onHeartbeatMissed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "panicButton",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRecoveryKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLivenessConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSafeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startGracePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleLiveness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace BeneficiaryAddedEvent {
  export type InputTuple = [wallet: AddressLike, shareBps: BigNumberish];
  export type OutputTuple = [wallet: string, shareBps: bigint];
  export interface OutputObject {
    wallet: string;
    shareBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BeneficiaryRemovedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfigUpdatedEvent {
  export type InputTuple = [key: string];
  export type OutputTuple = [key: string];
  export interface OutputObject {
    key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvacuationTriggeredEvent {
  export type InputTuple = [trigger: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [trigger: string, timestamp: bigint];
  export interface OutputObject {
    trigger: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GracePeriodStartedEvent {
  export type InputTuple = [deadline: BigNumberish];
  export type OutputTuple = [deadline: bigint];
  export interface OutputObject {
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeartbeatMissedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HeartbeatRecordedEvent {
  export type InputTuple = [
    sender: AddressLike,
    timestamp: BigNumberish,
    signature: BytesLike
  ];
  export type OutputTuple = [
    sender: string,
    timestamp: bigint,
    signature: string
  ];
  export interface OutputObject {
    sender: string;
    timestamp: bigint;
    signature: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InheritanceExecutedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InheritanceTransferEvent {
  export type InputTuple = [beneficiary: AddressLike, amount: BigNumberish];
  export type OutputTuple = [beneficiary: string, amount: bigint];
  export interface OutputObject {
    beneficiary: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PanicButtonPressedEvent {
  export type InputTuple = [sender: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [sender: string, timestamp: bigint];
  export interface OutputObject {
    sender: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryKeyRegisteredEvent {
  export type InputTuple = [recoveryKey: AddressLike];
  export type OutputTuple = [recoveryKey: string];
  export interface OutputObject {
    recoveryKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LegacyKeeper extends BaseContract {
  connect(runner?: ContractRunner | null): LegacyKeeper;
  waitForDeployment(): Promise<this>;

  interface: LegacyKeeperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addBeneficiary: TypedContractMethod<
    [wallet: AddressLike, shareBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  beneficiaries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        wallet: string;
        shareBps: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;

  cancelInheritance: TypedContractMethod<[], [void], "nonpayable">;

  evacuate: TypedContractMethod<
    [recoverySignature: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;

  evacuationExecuted: TypedContractMethod<[], [boolean], "view">;

  evacuationTimestamp: TypedContractMethod<[], [bigint], "view">;

  executeInheritance: TypedContractMethod<[], [void], "nonpayable">;

  getBeneficiaries: TypedContractMethod<
    [],
    [LegacyKeeper.BeneficiaryStructOutput[]],
    "view"
  >;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getLivenessStatus: TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean, boolean] & {
        lastHeartbeat: bigint;
        timeSinceHeartbeat: bigint;
        active: boolean;
        expired: boolean;
      }
    ],
    "view"
  >;

  getTimeoutStatus: TypedContractMethod<
    [],
    [
      [boolean, boolean] & {
        timeoutExceeded: boolean;
        gracePeriodElapsed: boolean;
      }
    ],
    "view"
  >;

  heartbeat: TypedContractMethod<[signature: BytesLike], [void], "nonpayable">;

  inheritanceExecuted: TypedContractMethod<[], [boolean], "view">;

  inheritanceTimestamp: TypedContractMethod<[], [bigint], "view">;

  isBeneficiary: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  liveness: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        heartbeatInterval: bigint;
        timeoutDuration: bigint;
        gracePeriod: bigint;
        lastHeartbeat: bigint;
        livenessActive: boolean;
      }
    ],
    "view"
  >;

  onHeartbeatMissed: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  panicButton: TypedContractMethod<
    [recoverySignature: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;

  registerRecoveryKey: TypedContractMethod<
    [recoveryKey: AddressLike],
    [void],
    "nonpayable"
  >;

  removeBeneficiary: TypedContractMethod<
    [wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setLivenessConfig: TypedContractMethod<
    [
      heartbeatInterval_: BigNumberish,
      timeoutDuration_: BigNumberish,
      gracePeriod_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setSafeVault: TypedContractMethod<
    [vaultAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  startGracePeriod: TypedContractMethod<
    [deadline: BigNumberish],
    [void],
    "nonpayable"
  >;

  toggleLiveness: TypedContractMethod<[active: boolean], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<
    [],
    [
      [string, string, boolean, boolean] & {
        safeVault: string;
        recoveryKeyAddress: string;
        recoveryKeyRegistered: boolean;
        privateRoutingEnabled: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addBeneficiary"
  ): TypedContractMethod<
    [wallet: AddressLike, shareBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beneficiaries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, boolean] & {
        wallet: string;
        shareBps: bigint;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelInheritance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "evacuate"
  ): TypedContractMethod<
    [recoverySignature: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "evacuationExecuted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "evacuationTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeInheritance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBeneficiaries"
  ): TypedContractMethod<[], [LegacyKeeper.BeneficiaryStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLivenessStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean, boolean] & {
        lastHeartbeat: bigint;
        timeSinceHeartbeat: bigint;
        active: boolean;
        expired: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTimeoutStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, boolean] & {
        timeoutExceeded: boolean;
        gracePeriodElapsed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "heartbeat"
  ): TypedContractMethod<[signature: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "inheritanceExecuted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "inheritanceTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isBeneficiary"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "liveness"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        heartbeatInterval: bigint;
        timeoutDuration: bigint;
        gracePeriod: bigint;
        lastHeartbeat: bigint;
        livenessActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "onHeartbeatMissed"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "panicButton"
  ): TypedContractMethod<
    [recoverySignature: BytesLike, message: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerRecoveryKey"
  ): TypedContractMethod<[recoveryKey: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeBeneficiary"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLivenessConfig"
  ): TypedContractMethod<
    [
      heartbeatInterval_: BigNumberish,
      timeoutDuration_: BigNumberish,
      gracePeriod_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSafeVault"
  ): TypedContractMethod<[vaultAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startGracePeriod"
  ): TypedContractMethod<[deadline: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleLiveness"
  ): TypedContractMethod<[active: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<
    [],
    [
      [string, string, boolean, boolean] & {
        safeVault: string;
        recoveryKeyAddress: string;
        recoveryKeyRegistered: boolean;
        privateRoutingEnabled: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BeneficiaryAdded"
  ): TypedContractEvent<
    BeneficiaryAddedEvent.InputTuple,
    BeneficiaryAddedEvent.OutputTuple,
    BeneficiaryAddedEvent.OutputObject
  >;
  getEvent(
    key: "BeneficiaryRemoved"
  ): TypedContractEvent<
    BeneficiaryRemovedEvent.InputTuple,
    BeneficiaryRemovedEvent.OutputTuple,
    BeneficiaryRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ConfigUpdated"
  ): TypedContractEvent<
    ConfigUpdatedEvent.InputTuple,
    ConfigUpdatedEvent.OutputTuple,
    ConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EvacuationTriggered"
  ): TypedContractEvent<
    EvacuationTriggeredEvent.InputTuple,
    EvacuationTriggeredEvent.OutputTuple,
    EvacuationTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "GracePeriodStarted"
  ): TypedContractEvent<
    GracePeriodStartedEvent.InputTuple,
    GracePeriodStartedEvent.OutputTuple,
    GracePeriodStartedEvent.OutputObject
  >;
  getEvent(
    key: "HeartbeatMissed"
  ): TypedContractEvent<
    HeartbeatMissedEvent.InputTuple,
    HeartbeatMissedEvent.OutputTuple,
    HeartbeatMissedEvent.OutputObject
  >;
  getEvent(
    key: "HeartbeatRecorded"
  ): TypedContractEvent<
    HeartbeatRecordedEvent.InputTuple,
    HeartbeatRecordedEvent.OutputTuple,
    HeartbeatRecordedEvent.OutputObject
  >;
  getEvent(
    key: "InheritanceExecuted"
  ): TypedContractEvent<
    InheritanceExecutedEvent.InputTuple,
    InheritanceExecutedEvent.OutputTuple,
    InheritanceExecutedEvent.OutputObject
  >;
  getEvent(
    key: "InheritanceTransfer"
  ): TypedContractEvent<
    InheritanceTransferEvent.InputTuple,
    InheritanceTransferEvent.OutputTuple,
    InheritanceTransferEvent.OutputObject
  >;
  getEvent(
    key: "PanicButtonPressed"
  ): TypedContractEvent<
    PanicButtonPressedEvent.InputTuple,
    PanicButtonPressedEvent.OutputTuple,
    PanicButtonPressedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryKeyRegistered"
  ): TypedContractEvent<
    RecoveryKeyRegisteredEvent.InputTuple,
    RecoveryKeyRegisteredEvent.OutputTuple,
    RecoveryKeyRegisteredEvent.OutputObject
  >;

  filters: {
    "BeneficiaryAdded(address,uint16)": TypedContractEvent<
      BeneficiaryAddedEvent.InputTuple,
      BeneficiaryAddedEvent.OutputTuple,
      BeneficiaryAddedEvent.OutputObject
    >;
    BeneficiaryAdded: TypedContractEvent<
      BeneficiaryAddedEvent.InputTuple,
      BeneficiaryAddedEvent.OutputTuple,
      BeneficiaryAddedEvent.OutputObject
    >;

    "BeneficiaryRemoved(address)": TypedContractEvent<
      BeneficiaryRemovedEvent.InputTuple,
      BeneficiaryRemovedEvent.OutputTuple,
      BeneficiaryRemovedEvent.OutputObject
    >;
    BeneficiaryRemoved: TypedContractEvent<
      BeneficiaryRemovedEvent.InputTuple,
      BeneficiaryRemovedEvent.OutputTuple,
      BeneficiaryRemovedEvent.OutputObject
    >;

    "ConfigUpdated(string)": TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;
    ConfigUpdated: TypedContractEvent<
      ConfigUpdatedEvent.InputTuple,
      ConfigUpdatedEvent.OutputTuple,
      ConfigUpdatedEvent.OutputObject
    >;

    "EvacuationTriggered(address,uint256)": TypedContractEvent<
      EvacuationTriggeredEvent.InputTuple,
      EvacuationTriggeredEvent.OutputTuple,
      EvacuationTriggeredEvent.OutputObject
    >;
    EvacuationTriggered: TypedContractEvent<
      EvacuationTriggeredEvent.InputTuple,
      EvacuationTriggeredEvent.OutputTuple,
      EvacuationTriggeredEvent.OutputObject
    >;

    "GracePeriodStarted(uint256)": TypedContractEvent<
      GracePeriodStartedEvent.InputTuple,
      GracePeriodStartedEvent.OutputTuple,
      GracePeriodStartedEvent.OutputObject
    >;
    GracePeriodStarted: TypedContractEvent<
      GracePeriodStartedEvent.InputTuple,
      GracePeriodStartedEvent.OutputTuple,
      GracePeriodStartedEvent.OutputObject
    >;

    "HeartbeatMissed(uint256)": TypedContractEvent<
      HeartbeatMissedEvent.InputTuple,
      HeartbeatMissedEvent.OutputTuple,
      HeartbeatMissedEvent.OutputObject
    >;
    HeartbeatMissed: TypedContractEvent<
      HeartbeatMissedEvent.InputTuple,
      HeartbeatMissedEvent.OutputTuple,
      HeartbeatMissedEvent.OutputObject
    >;

    "HeartbeatRecorded(address,uint256,bytes)": TypedContractEvent<
      HeartbeatRecordedEvent.InputTuple,
      HeartbeatRecordedEvent.OutputTuple,
      HeartbeatRecordedEvent.OutputObject
    >;
    HeartbeatRecorded: TypedContractEvent<
      HeartbeatRecordedEvent.InputTuple,
      HeartbeatRecordedEvent.OutputTuple,
      HeartbeatRecordedEvent.OutputObject
    >;

    "InheritanceExecuted(uint256)": TypedContractEvent<
      InheritanceExecutedEvent.InputTuple,
      InheritanceExecutedEvent.OutputTuple,
      InheritanceExecutedEvent.OutputObject
    >;
    InheritanceExecuted: TypedContractEvent<
      InheritanceExecutedEvent.InputTuple,
      InheritanceExecutedEvent.OutputTuple,
      InheritanceExecutedEvent.OutputObject
    >;

    "InheritanceTransfer(address,uint256)": TypedContractEvent<
      InheritanceTransferEvent.InputTuple,
      InheritanceTransferEvent.OutputTuple,
      InheritanceTransferEvent.OutputObject
    >;
    InheritanceTransfer: TypedContractEvent<
      InheritanceTransferEvent.InputTuple,
      InheritanceTransferEvent.OutputTuple,
      InheritanceTransferEvent.OutputObject
    >;

    "PanicButtonPressed(address,uint256)": TypedContractEvent<
      PanicButtonPressedEvent.InputTuple,
      PanicButtonPressedEvent.OutputTuple,
      PanicButtonPressedEvent.OutputObject
    >;
    PanicButtonPressed: TypedContractEvent<
      PanicButtonPressedEvent.InputTuple,
      PanicButtonPressedEvent.OutputTuple,
      PanicButtonPressedEvent.OutputObject
    >;

    "RecoveryKeyRegistered(address)": TypedContractEvent<
      RecoveryKeyRegisteredEvent.InputTuple,
      RecoveryKeyRegisteredEvent.OutputTuple,
      RecoveryKeyRegisteredEvent.OutputObject
    >;
    RecoveryKeyRegistered: TypedContractEvent<
      RecoveryKeyRegisteredEvent.InputTuple,
      RecoveryKeyRegisteredEvent.OutputTuple,
      RecoveryKeyRegisteredEvent.OutputObject
    >;
  };
}
